import OpenAI from 'openai';
import * as cheerio from 'cheerio';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const FAL_KEY = process.env.FAL_KEY;

// Generate Image using Fal.ai (Flux) and save locally
export async function generateAndSaveImage(prompt: string): Promise<string> {
  console.log('Generating image for prompt:', prompt);
  
  const response = await fetch('https://fal.run/fal-ai/flux-schnell', {
    method: 'POST',
    headers: {
      'Authorization': `Key ${FAL_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      prompt: prompt,
      image_size: 'landscape_4_3',
      num_inference_steps: 4,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error('Fal.ai error:', error);
    throw new Error('Image generation failed');
  }

  const data = await response.json();
  const imageUrl = data.images[0].url;

  // Download the image and save to public/uploads
  const imageRes = await fetch(imageUrl);
  const arrayBuffer = await imageRes.arrayBuffer();
  const buffer = Buffer.from(arrayBuffer);

  const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1e9)}`;
  const filename = `ai-${uniqueSuffix}.jpg`;
  const uploadDir = join(process.cwd(), 'public', 'uploads');
  
  try { await mkdir(uploadDir, { recursive: true }); } catch (e) {}

  await writeFile(join(uploadDir, filename), buffer);
  
  return `/uploads/${filename}`;
}

export async function scrapeUrl(url: string): Promise<string> {
  const res = await fetch(url);
  const html = await res.text();
  const $ = cheerio.load(html);
  
  // Remove script and style elements
  $('script, style, nav, footer, header').remove();
  
  return $('body').text().replace(/\s+/g, ' ').trim();
}

export async function generateArticlePayload(mode: 'KEYWORD' | 'URL' | 'TEXT', input: string) {
  let sourceText = input;
  
  if (mode === 'URL') {
    sourceText = await scrapeUrl(input);
  }

  const prompt = `
    You are an expert Content Writer and SEO/AEO (Answer Engine Optimization) specialist.
    I need you to write/rewrite a highly engaging, SEO-optimized article.
    
    Mode: ${mode}
    Input Data: ${sourceText}

    Rules:
    1. Structure the article with H2 and H3 tags.
    2. Include a FAQ section at the end (AEO best practice).
    3. The content must be formatted in clean HTML (no markdown tags like \`\`\`html).
    4. Write in a modern, professional, yet brutal/no-nonsense editorial tone.
    5. I need 2 images inside the text. Place placeholders exactly like this: [IMAGE_PLACEHOLDER_1] and [IMAGE_PLACEHOLDER_2] in the HTML content where appropriate.
    6. Provide a detailed prompt for the cover image (to be generated by AI).
    7. Provide detailed prompts for the 2 in-text images.

    Return the response as a valid JSON object:
    {
      "title": "SEO Optimized Title",
      "excerpt": "A short 2 sentence excerpt.",
      "content": "<h1>...</h1>...[IMAGE_PLACEHOLDER_1]...",
      "coverImagePrompt": "High quality editorial photo of...",
      "inTextImagePrompts": [
        "Prompt for image 1...",
        "Prompt for image 2..."
      ]
    }
  `;

  const completion = await openai.chat.completions.create({
    messages: [{ role: 'system', content: prompt }],
    model: 'gpt-4o',
    response_format: { type: 'json_object' },
  });

  const rawJson = completion.choices[0].message.content || '{}';
  const result = JSON.parse(rawJson);

  // Generate Images
  const coverImageUrl = await generateAndSaveImage(result.coverImagePrompt);
  
  let finalContent = result.content;
  if (result.inTextImagePrompts && result.inTextImagePrompts.length > 0) {
    for (let i = 0; i < result.inTextImagePrompts.length; i++) {
      const prompt = result.inTextImagePrompts[i];
      try {
        const url = await generateAndSaveImage(prompt);
        finalContent = finalContent.replace(`[IMAGE_PLACEHOLDER_${i + 1}]`, `<img src="${url}" alt="Article Image" class="w-full rounded-2xl my-8 shadow-lg" />`);
      } catch (e) {
        console.error('Failed to generate in-text image', e);
      }
    }
  }

  return {
    title: result.title,
    excerpt: result.excerpt,
    content: finalContent,
    coverImage: coverImageUrl,
  };
}
